services:
  postgres:
    image: postgres:15-alpine
    container_name: fleet_postgres
    environment:
      POSTGRES_DB: fleet_db
      POSTGRES_USER: fleet_admin
      POSTGRES_PASSWORD: fleet_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleet_admin -d fleet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: fleet_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      # - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    command: mosquitto -c /mosquitto-no-auth.conf 

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: fleet_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
  rabbitmq_data: