services:
  postgres:
    image: postgres:15-alpine
    container_name: fleet_postgres
    environment:
      POSTGRES_DB: fleet_db
      POSTGRES_USER: fleet_admin
      POSTGRES_PASSWORD: fleet_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleet_admin -d fleet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: